export const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES"

export const REMOVE_FROM_FAVOURITES = "REMOVE_FROM_FAVOURITES"

export const JOB_DETAILS_ADDED = "JOB_DETAILS_ADDED"

export const FETCH_COMPANIES = "FETCH_COMPANIES"

export const FETCH_COMPANIES_ERROR = "FETCH_COMPANIES_ERROR"

export const FETCH_COMPANIES_LOADING = "FETCH_COMPANIES_LOADING"

export const FETCH_JOBS = "FETCH_JOBS"

export const FETCH_JOBS_ERROR = "FETCH_JOBS_ERROR"

export const FETCH_JOBS_LOADING = "FETCH_JOBS_LOADING"

export const FETCH_CATEGORIES = "FETCH_CATEGORIES"

export const FETCH_CATEGORIES_ERROR = "RFETCH_CATEGORIES_ERROR"

export const FETCH_CATEGORIES_LOADING = "RFETCH_CATEGORIES_LOADING"

export const FETCH_CATEGORY_JOBS = "FETCH_CATEGORY_JOBS"

export const FETCH_CATEGORY_JOBS_ERROR = "FETCH_CATEGORY_JOBS_ERROR"

export const FETCH_CATEGORY_JOBS_LOADING = "FETCH_CATEGORY_JOBS_LOADING"
